cc_binary(
    name = "part1",
    srcs = ["main_1.cpp"],
    data = ["input.txt"],
    linkopts = ["-pthread"],
)

cc_binary(
    name = "part2",
    srcs = ["main_2.cpp"],
    data = ["input.txt"],
    linkopts = ["-pthread"],
    copts = ["-std=c++17"]
)
